common:
  img_topic: "/infrared/image_raw"
  lid_topic: "/velodyne_points"  
  imu_topic: "/I300"
  img_en: 1
  lidar_en: 1
  # m2dgr_en: 1
  ros_driver_bug_fix: false
  
extrin_calib:    
  #  lidar -> imu
  extrinsic_T: [ -0.09, -0.067, -0.188]
  extrinsic_R: [1, 0, 0, 0, -1, 0, 0, 0, -1]
  #  lidar -> camera
  Rcl: [0,-1,0,
        0,0,-1,
        1,0,0]
  Pcl: [0.158, 0, -0.188] 

time_offset:
  imu_time_offset: 0.0
  img_time_offset: 0.0  # 0.1不好
  exposure_time_init: 0.0

preprocess:
  # point_filter_num: 2 
  # filter_size_surf: 0.1
  lidar_type: 2
  scan_line: 32
  blind: 1.5
  feature_extract_enabled: false  # true rmse	0.819060

vio:                                   
  # max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 减小该值会增加视觉信息权重，使系统更依赖视觉特征；增大则降低视觉权重，适用于视觉退化场景（如低纹理区域）
  patch_size: 8
  patch_pyrimid_level: 3
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1         # 默认值：0.2

imu:
  imu_en: true
  imu_int_frame: 30
  # acc_cov: 3.7686306102624571e-02
  # gyr_cov: 2.3417543020438883e-03
  # b_acc_cov: 1.1416642385952368e-03
  # b_gyr_cov: 1.4428407712885209e-05
  acc_cov: 0.5   # (acc_n)^2 = 0.0164
  gyr_cov: 0.1  # (gyr_n)^2 = 0.000454
  b_acc_cov: 0.0001  # (acc_w)^2 = 8.1e-09
  b_gyr_cov: 0.0001  # (gyr_w)^2 = 3.47e-11

lio:
  max_iterations: 5
  dept_err: 0.02       
  beam_err: 0.05        
  min_eigen_value: 0.005
  voxel_size: 2 
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:
  map_sliding_en: true
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: false

publish:
  dense_map_en: true
  pub_effect_point_en: false
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "city01"
  pose_output_en: true

pcd_save:
  pcd_save_en: true
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
